FROM python:3.8-slim

RUN useradd PACKAGE_NAME
WORKDIR /home/PACKAGE_NAME

RUN apt update && apt install -y gcc git build-essential
COPY --chown=PACKAGE_NAME:PACKAGE_NAME pyproject.toml pyproject.toml
COPY --chown=PACKAGE_NAME:PACKAGE_NAME poetry.lock poetry.lock

RUN python -m pip install poetry
RUN python -m poetry config virtualenvs.create false
RUN python -m poetry install --no-root --no-interaction && rm -rf ~/.cache/pypoetry/{cache,artifacts}

RUN chown PACKAGE_NAME:PACKAGE_NAME /home/PACKAGE_NAME

ENV SHELL /bin/bash

USER PACKAGE_NAME
