site_name: PACKAGE_NAME
repo_url: https://github.com/lambda-science/PACKAGE_NAME
site_url: https://lambda-science.github.io/PACKAGE_NAME/
site_description: PACKAGE_NAME - 
site_author: Corentin Meyer

nav:
  - Home: index.md
  - Getting Started:
    - Quickstart: quickstart/index.md
    - Advanced: quickstart/advanced.md
    - FAQ: quickstart/faq.md
  - Examples:
    - Example: examples/example.md
  - API:
    - PACKAGE_NAME: api/PACKAGE_NAME.md
plugins:
  - mkdocstrings
  - search
copyright: Maintained by <a href="https://twitter.com/corentinm_py">Corentin Meyer</a>.
theme:
  name: material
  favicon: icon.png
  logo: icon.png
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      toggle:
        icon: material/lightbulb  
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.top
    - search.suggest
    - search.highlight
markdown_extensions:
  - attr_list
  - admonition
  - tables
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
