name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black
      # Include `--format=github` to enable automatic inline annotations.
      - name: Run Ruff
        run: ruff --format=github PACKAGE_NAME
      - name: Black
        run: |
          black --diff --target-version py38 PACKAGE_NAME tests
          black --check --target-version py38 PACKAGE_NAME tests